version: '3'

services:
  # Public API to get any data from the database
  api-get-express:
    build: ./api-get-express/
    image: api-get-express
    container_name: api-get-express
    restart: unless-stopped
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    networks:
        - traefik-network

  # Private API who work with the keycloak server to authenticate the user and modify the database
  api-python:
    build: ./api-python/
    image: api-python
    container_name: api-python
    restart: unless-stopped
    depends_on:
        - postgresql
        - keycloak
        - api-get-express
    networks:
      - traefik-network
    ports:
      - 5001:5001

  # Database to store all the data
  postgresql:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - traefik-network

  # Reverse proxy to redirect the request to the good container
  apache-oidc:
    build: ./apache-oidc
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      OIDC_PROVIDER_METADATA_URL: http://keycloak:8080/realms/deadpoetssociety/.well-known/openid-configuration
      OIDC_CLIENT_ID: apache-oidc
      OIDC_CLIENT_SECRET: 654ckxBaivlZkQVOzcyuWrsGnfDxc3mQ
      OIDC_CRYPTO_PASSPHRASE: theMegaPassPhraseOfTheDeath

  # Keycloak server to authenticate the user
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - traefik-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    command: start-dev --import-realm --proxy edge --hostname-strict=false --hostname-url="https://dps.epita.local/auth" --hostname-admin-url="https://dps.epita.local/auth"

volumes:
  # Volume to store keycloak config
  pgdata:

  # Volume to store the database
  db:
    driver: local

networks:
    # Network to connect the api to traefik (reverse proxy)
    traefik-network:



